In [3]:
import torch
from usta_model import UstaModel
from usta_tokenizer import UstaTokenizer

u_tokenizer = UstaTokenizer("tokenizer.json")

prompt = "Artificial is intelligence is transforming the way people the interact with technology"
tokens = u_tokenizer.encode(prompt)

tokens.shape

torch.Size([23])

In [4]:
torch.manual_seed(1)
u_model = UstaModel(vocab_size=len(u_tokenizer.vocab),embedding_dim = 4,context_length= 23)

sentence_meanings_with_attention_context = u_model(tokens)
sentence_meanings_with_attention_context

tensor([[ 0.7754, -2.0158,  1.2589,  0.9274],
        [ 0.1518, -0.3947,  0.2465,  0.1816],
        [ 0.2830, -0.4972,  0.1890,  0.2198],
        [-0.2476, -0.8403,  0.1502,  0.2836],
        [ 0.1441, -0.3747,  0.2340,  0.1724],
        [-0.0188, -1.1740,  0.7665,  0.5385],
        [ 0.7172, -0.3227,  0.7893,  0.3618],
        [ 1.2497, -0.2902,  1.2898,  0.5575],
        [ 0.1508,  0.1714,  0.0108, -0.0402],
        [-0.0049, -0.1299, -0.0379,  0.0548],
        [ 0.8808, -0.3023,  0.7498,  0.3695],
        [ 0.3098,  0.0163,  0.2523,  0.0679],
        [-0.3261, -0.6810,  0.1387,  0.2183],
        [ 0.2769,  0.1470,  0.2492,  0.0483],
        [-0.1385, -0.6377,  0.2747,  0.2754],
        [-0.2640, -0.9990,  0.3374,  0.3937],
        [ 0.2628, -0.2392,  0.4765,  0.2630],
        [-0.1370, -0.3610,  0.1787,  0.1535],
        [-0.7633, -0.7307, -0.1347,  0.1377],
        [-0.0135, -0.6136,  0.3293,  0.2971],
        [-0.2152, -0.3195,  0.1834,  0.1489],
        [-0.0181, -0.4923,  0.1343

In [5]:
from transformers import Gemma3ForCausalLM
gemma_model = Gemma3ForCausalLM.from_pretrained("google/gemma-3-1b-it")
u_model ,gemma_model

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 340/340 [00:00<00:00, 5390.75it/s]


(UstaModel(
   (embedding): Embedding(65, 4)
   (pos_embedding): Embedding(23, 4)
   (self_attention): UstaCasualAttention(
     (q_weights): Linear(in_features=4, out_features=4, bias=False)
     (k_weights): Linear(in_features=4, out_features=4, bias=False)
     (v_weights): Linear(in_features=4, out_features=4, bias=False)
     (dropout): Dropout(p=0.5, inplace=False)
   )
 ),
 Gemma3ForCausalLM(
   (model): Gemma3TextModel(
     (embed_tokens): Gemma3TextScaledWordEmbedding(262144, 1152, padding_idx=0)
     (layers): ModuleList(
       (0-25): 26 x Gemma3DecoderLayer(
         (self_attn): Gemma3Attention(
           (q_proj): Linear(in_features=1152, out_features=1024, bias=False)
           (k_proj): Linear(in_features=1152, out_features=256, bias=False)
           (v_proj): Linear(in_features=1152, out_features=256, bias=False)
           (o_proj): Linear(in_features=1024, out_features=1152, bias=False)
           (q_norm): Gemma3RMSNorm((256,), eps=1e-06)
           (k_norm): G

In [6]:
u_tokenizer.tokenize(prompt)

['artificial',
 ' ',
 'is',
 ' ',
 'intelligence',
 ' ',
 'is',
 ' ',
 'transforming',
 ' ',
 'the',
 ' ',
 'way',
 ' ',
 'people',
 ' ',
 'the',
 ' ',
 'interact',
 ' ',
 'with',
 ' ',
 'technology']

In [7]:
from plot_tokens import plot_tokens 

u_sentences = [
    {
        "words" : sentence_meanings_with_attention_context.detach().numpy(),
        "labels" : u_tokenizer.tokenize(prompt),
        "color" : "red"
    }
]
plot_tokens(u_sentences ,"Models Context Space")

In [8]:
sentence_meanings_with_attention_context

tensor([[ 0.7754, -2.0158,  1.2589,  0.9274],
        [ 0.1518, -0.3947,  0.2465,  0.1816],
        [ 0.2830, -0.4972,  0.1890,  0.2198],
        [-0.2476, -0.8403,  0.1502,  0.2836],
        [ 0.1441, -0.3747,  0.2340,  0.1724],
        [-0.0188, -1.1740,  0.7665,  0.5385],
        [ 0.7172, -0.3227,  0.7893,  0.3618],
        [ 1.2497, -0.2902,  1.2898,  0.5575],
        [ 0.1508,  0.1714,  0.0108, -0.0402],
        [-0.0049, -0.1299, -0.0379,  0.0548],
        [ 0.8808, -0.3023,  0.7498,  0.3695],
        [ 0.3098,  0.0163,  0.2523,  0.0679],
        [-0.3261, -0.6810,  0.1387,  0.2183],
        [ 0.2769,  0.1470,  0.2492,  0.0483],
        [-0.1385, -0.6377,  0.2747,  0.2754],
        [-0.2640, -0.9990,  0.3374,  0.3937],
        [ 0.2628, -0.2392,  0.4765,  0.2630],
        [-0.1370, -0.3610,  0.1787,  0.1535],
        [-0.7633, -0.7307, -0.1347,  0.1377],
        [-0.0135, -0.6136,  0.3293,  0.2971],
        [-0.2152, -0.3195,  0.1834,  0.1489],
        [-0.0181, -0.4923,  0.1343

![image.png](https://lena-voita.github.io/resources/lectures/seq2seq/transformer/qkv_attention_formula-min.png)


In [9]:
q_weights = torch.nn.Linear(4,3 , bias= False)
k_weights = torch.nn.Linear(4,3 , bias= False)
v_weights = torch.nn.Linear(4,3 , bias= False)

q_of_sentence = q_weights(sentence_meanings_with_attention_context)
k_of_sentence = k_weights(sentence_meanings_with_attention_context)
v_of_sentence = v_weights(sentence_meanings_with_attention_context)

q_of_sentence.shape ,k_of_sentence.shape ,v_of_sentence.shape

(torch.Size([23, 3]), torch.Size([23, 3]), torch.Size([23, 3]))

In [10]:
attention_scores = q_of_sentence @ k_of_sentence.T
attention_weights = torch.softmax(attention_scores / k_of_sentence.shape[-1] ** 0.5 , dim = 1)

context_vector = attention_weights @ v_of_sentence
context_vector

tensor([[ 0.3618,  0.1203, -0.0218],
        [ 0.3619,  0.1218, -0.0194],
        [ 0.3613,  0.1217, -0.0193],
        [ 0.3583,  0.1204, -0.0194],
        [ 0.3619,  0.1219, -0.0194],
        [ 0.3613,  0.1208, -0.0207],
        [ 0.3675,  0.1236, -0.0202],
        [ 0.3729,  0.1254, -0.0208],
        [ 0.3632,  0.1228, -0.0188],
        [ 0.3612,  0.1220, -0.0187],
        [ 0.3678,  0.1239, -0.0200],
        [ 0.3644,  0.1229, -0.0193],
        [ 0.3588,  0.1206, -0.0194],
        [ 0.3651,  0.1233, -0.0192],
        [ 0.3605,  0.1213, -0.0195],
        [ 0.3589,  0.1204, -0.0197],
        [ 0.3650,  0.1231, -0.0195],
        [ 0.3611,  0.1216, -0.0193],
        [ 0.3559,  0.1197, -0.0190],
        [ 0.3613,  0.1216, -0.0195],
        [ 0.3613,  0.1217, -0.0193],
        [ 0.3604,  0.1214, -0.0192],
        [ 0.3608,  0.1213, -0.0196]], grad_fn=<MmBackward0>)

In [11]:
from plot_tokens import plot_tokens
u_sentences = [
    {
        "words" : q_of_sentence.detach().numpy(),
        "labels" : u_tokenizer.tokenize(prompt),
        "color" : "blue",
    },
    {
        "words" : k_of_sentence.detach().numpy(),
        "labels" : u_tokenizer.tokenize(prompt),
        "color" : "purple",
    }, 
    {
        "words" : v_of_sentence.detach().numpy(),
        "labels" : u_tokenizer.tokenize(prompt),
        "color" : "orange",
    },
    {
        "words" : context_vector.detach().numpy(),
        "labels" : u_tokenizer.tokenize(prompt),
        "color" : "green",
    },
]
plot_tokens(u_sentences ,"Query, Key , Value and Context Vector Space")

## Casual Self Attention

In [12]:
attention_weights

tensor([[0.0416, 0.0438, 0.0440, 0.0427, 0.0439, 0.0419, 0.0442, 0.0444, 0.0449,
         0.0442, 0.0445, 0.0446, 0.0428, 0.0447, 0.0430, 0.0422, 0.0439, 0.0435,
         0.0423, 0.0431, 0.0434, 0.0435, 0.0428],
        [0.0431, 0.0435, 0.0436, 0.0433, 0.0436, 0.0432, 0.0436, 0.0437, 0.0437,
         0.0436, 0.0437, 0.0437, 0.0433, 0.0437, 0.0434, 0.0432, 0.0436, 0.0435,
         0.0433, 0.0434, 0.0435, 0.0435, 0.0433],
        [0.0429, 0.0436, 0.0436, 0.0433, 0.0436, 0.0431, 0.0436, 0.0436, 0.0438,
         0.0437, 0.0436, 0.0437, 0.0434, 0.0438, 0.0434, 0.0432, 0.0436, 0.0435,
         0.0433, 0.0434, 0.0435, 0.0435, 0.0434],
        [0.0410, 0.0438, 0.0438, 0.0431, 0.0438, 0.0421, 0.0436, 0.0434, 0.0447,
         0.0443, 0.0437, 0.0444, 0.0433, 0.0445, 0.0433, 0.0427, 0.0438, 0.0437,
         0.0433, 0.0433, 0.0437, 0.0437, 0.0431],
        [0.0431, 0.0435, 0.0436, 0.0433, 0.0436, 0.0432, 0.0436, 0.0437, 0.0437,
         0.0436, 0.0437, 0.0437, 0.0434, 0.0437, 0.0434, 0.0432, 0.0436

In [13]:
mask = torch.tril(torch.ones(attention_weights.shape[0], attention_weights.shape[0]))
mask

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.],
 

![softmax](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8xAwSzCWtMxJJjg9auOpDfFoUdFsgZDaFbKUV0saKgw&s=10)


In [14]:
mask = torch.tril(torch.ones(attention_weights.shape[0], attention_weights.shape[0]))
masked_attention_weights = attention_weights.masked_fill(mask == 0, -torch.inf)
masked_attention_weights

torch.softmax(masked_attention_weights ,dim = 1)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4999, 0.5001, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3332, 0.3334, 0.3334, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2495, 0.2502, 0.2502, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1999, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000

In [15]:
dropout_rate = 0
torch.manual_seed(1)
dropout = torch.nn.Dropout(dropout_rate)
dropout(attention_weights)

tensor([[0.0416, 0.0438, 0.0440, 0.0427, 0.0439, 0.0419, 0.0442, 0.0444, 0.0449,
         0.0442, 0.0445, 0.0446, 0.0428, 0.0447, 0.0430, 0.0422, 0.0439, 0.0435,
         0.0423, 0.0431, 0.0434, 0.0435, 0.0428],
        [0.0431, 0.0435, 0.0436, 0.0433, 0.0436, 0.0432, 0.0436, 0.0437, 0.0437,
         0.0436, 0.0437, 0.0437, 0.0433, 0.0437, 0.0434, 0.0432, 0.0436, 0.0435,
         0.0433, 0.0434, 0.0435, 0.0435, 0.0433],
        [0.0429, 0.0436, 0.0436, 0.0433, 0.0436, 0.0431, 0.0436, 0.0436, 0.0438,
         0.0437, 0.0436, 0.0437, 0.0434, 0.0438, 0.0434, 0.0432, 0.0436, 0.0435,
         0.0433, 0.0434, 0.0435, 0.0435, 0.0434],
        [0.0410, 0.0438, 0.0438, 0.0431, 0.0438, 0.0421, 0.0436, 0.0434, 0.0447,
         0.0443, 0.0437, 0.0444, 0.0433, 0.0445, 0.0433, 0.0427, 0.0438, 0.0437,
         0.0433, 0.0433, 0.0437, 0.0437, 0.0431],
        [0.0431, 0.0435, 0.0436, 0.0433, 0.0436, 0.0432, 0.0436, 0.0437, 0.0437,
         0.0436, 0.0437, 0.0437, 0.0434, 0.0437, 0.0434, 0.0432, 0.0436

In [ ]:
from v1.usta_casual_attention import UstaCasualAttention
import torch
import torch.nn as nn 

class UstaMultiHeadAttention(nn.Module):
    def __init__(self,embedding_dim, output_dim,context_length,num_heads,dropout_rate = 0 ):
        super().__init__()

        self.heads = nn.ModuleList(
            [UstaCasualAttention(embedding_dim,output_dim,context_length,dropout_rate) for _ in range(num_heads)]
        )
    def forward(self, x):
        attention_outs = []
        for head in self.heads:
            head_out = head(x)
            attention_outs.append(head_out)

        return torch.cat(attention_outs ,dim = 1)

multi_head_attention = UstaMultiHeadAttention(4,4,23,2,dropout_rate=0)

out = multi_head_attention(torch.randn(4,4))
out.shape , out

(torch.Size([4, 8]),
 tensor([[-0.0604, -0.2597,  0.5058,  0.5355, -0.0396, -0.2885,  0.0354, -0.4319],
         [ 0.3153,  0.2359,  0.2991,  0.3882, -0.1279,  0.0932, -0.2569, -0.4420],
         [ 0.4003,  0.3683,  0.1317,  0.1788, -0.1114,  0.2624, -0.3261, -0.4174],
         [ 0.2552,  0.3572, -0.0390,  0.0843, -0.0044,  0.2488, -0.3413, -0.2092]],
        grad_fn=<CatBackward0>))