In [1]:
import torch
from usta_model import UstaModel
from usta_tokenizer import UstaTokenizer

u_tokenizer = UstaTokenizer("tokenizer.json")

prompt = "Artificial is intelligence is transforming the way people the interact with technology"
tokens = u_tokenizer.encode(prompt)

tokens

tensor([ 1, 63,  3, 63,  2, 63,  3, 63,  4, 63,  5, 63,  6, 63,  7, 63,  5, 63,
         8, 63,  9, 63, 10])

In [2]:
torch.manual_seed(1)
u_model = UstaModel(vocab_size=len(u_tokenizer.vocab),embedding_dim = 4,num_heads = 2,context_length= 23)

sentence_meanings_with_attention_context = u_model(tokens)
sentence_meanings_with_attention_context.shape

torch.Size([23, 4])

In [3]:
out = u_model(tokens)
out

tensor([[-0.1305, -0.4535,  0.1338,  0.1900],
        [-0.1935, -0.3172,  0.0909,  0.1245],
        [-0.3518, -0.3475,  0.0528,  0.1697],
        [-0.4175, -0.3265,  0.0190,  0.1575],
        [-0.1600, -0.3448,  0.0628,  0.0909],
        [-0.6514, -0.4455, -0.0503,  0.2390],
        [-0.0602, -0.4808, -0.0837, -0.0527],
        [-0.1647, -0.3396,  0.0682,  0.0966],
        [-0.2283, -0.4290,  0.0736,  0.1643],
        [-0.1784, -0.3285,  0.1018,  0.1329],
        [-0.3714, -0.3192,  0.0382,  0.1532],
        [-0.0702, -0.4875, -0.0844, -0.0466],
        [-0.3278, -0.5052,  0.0819,  0.2475],
        [-0.0654, -0.4725, -0.0840, -0.0538],
        [-0.3041, -0.3014,  0.0634,  0.1412],
        [-0.2198, -0.3658,  0.0274,  0.0896],
        [-0.1836, -0.3230,  0.0862,  0.1173],
        [-0.1448, -0.3663,  0.0550,  0.0841],
        [-0.2477, -0.3044,  0.0839,  0.1374],
        [-0.0788, -0.4571, -0.0553, -0.0243],
        [-0.2486, -0.3058,  0.0858,  0.1402],
        [-0.1302, -0.3862,  0.0305

In [4]:
u_model

UstaModel(
  (embedding): Embedding(65, 4)
  (pos_embedding): Embedding(23, 4)
  (self_attention): UstaMultiHeadAttention(
    (multi_head_attention): MultiheadAttention(
      (out_proj): NonDynamicallyQuantizableLinear(in_features=4, out_features=4, bias=True)
    )
    (projection): Linear(in_features=4, out_features=4, bias=True)
  )
  (norm): UstaLayerNorm()
  (mlp): UstaMLP(
    (gate_proj): Linear(in_features=4, out_features=4, bias=True)
    (up_proj): Linear(in_features=4, out_features=4, bias=True)
    (down_proj): Linear(in_features=4, out_features=4, bias=True)
    (gelu): GELU()
  )
)

In [5]:
example_tensor = torch.tensor([[1,2,3,],[4,5,6]], dtype = torch.float32)

mean = example_tensor.mean(dim= -1 ,keepdim=True)
var  = example_tensor.var(dim=-1,keepdim=True, unbiased = False)

mean,var, example_tensor

(tensor([[2.],
         [5.]]),
 tensor([[0.6667],
         [0.6667]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]))

In [6]:
from usta_layer_norm import UstaLayerNorm

norm_layer = UstaLayerNorm(4)
norm_layer(out)

tensor([[-0.2570, -1.5241,  0.7804,  1.0007],
        [-0.6397, -1.3005,  0.8804,  1.0598],
        [-0.9934, -0.9750,  0.7345,  1.2338],
        [-1.1607, -0.7772,  0.6773,  1.2607],
        [-0.4072, -1.4486,  0.8487,  1.0071],
        [-1.2298, -0.6331,  0.5123,  1.3506],
        [ 0.6059, -1.7283,  0.4754,  0.6470],
        [-0.4468, -1.4259,  0.8569,  1.0158],
        [-0.5208, -1.3679,  0.7530,  1.1357],
        [-0.5712, -1.3482,  0.8793,  1.0401],
        [-1.0960, -0.8640,  0.7244,  1.2356],
        [ 0.5586, -1.7270,  0.4805,  0.6880],
        [-0.6664, -1.2517,  0.6858,  1.2323],
        [ 0.5893, -1.7285,  0.4836,  0.6556],
        [-0.9974, -0.9842,  0.8003,  1.1812],
        [-0.5568, -1.3482,  0.7839,  1.1210],
        [-0.5843, -1.3391,  0.8774,  1.0460],
        [-0.2864, -1.5121,  0.8190,  0.9795],
        [-0.8445, -1.1352,  0.8531,  1.1267],
        [ 0.4261, -1.7213,  0.5595,  0.7357],
        [-0.8447, -1.1349,  0.8517,  1.1279],
        [-0.1339, -1.5804,  0.7740

In [7]:
!hf auth login

User is already logged in. Use `hf auth login --force` to force re-login.


In [8]:
%pip install transformers -U

Note: you may need to restart the kernel to use updated packages.


In [9]:
from transformers import AutoTokenizer , AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen3-0.6B")
q_model= AutoModelForCausalLM.from_pretrained("Qwen/Qwen3-0.6B")

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 311/311 [00:00<00:00, 4258.76it/s]


![transformer-architecture](https://deeprevision.github.io/posts/001-transformer/transformer.png)

In [10]:
q_model

Qwen3ForCausalLM(
  (model): Qwen3Model(
    (embed_tokens): Embedding(151936, 1024)
    (layers): ModuleList(
      (0-27): 28 x Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear(in_features=1024, out_features=2048, bias=False)
          (k_proj): Linear(in_features=1024, out_features=1024, bias=False)
          (v_proj): Linear(in_features=1024, out_features=1024, bias=False)
          (o_proj): Linear(in_features=2048, out_features=1024, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear(in_features=1024, out_features=3072, bias=False)
          (up_proj): Linear(in_features=1024, out_features=3072, bias=False)
          (down_proj): Linear(in_features=3072, out_features=1024, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): Qwen3RMSNorm((1024,), eps=1e-06)
        (post_attention_layer

![GELU-Formula](https://miro.medium.com/v2/resize:fit:1400/1*O5E-huBuY1UTHMmM--rhLQ.png)

In [11]:
import torch.nn as nn 

class GELU(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self,x):
        return 0.5 * x * (
            1 + torch.tanh(
                torch.sqrt(torch.tensor(2/torch.pi))*(x + 0.04471 * torch.pow(x,3))
            )
        )
 
gelu = GELU()
example_tensor = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)
gelu(example_tensor)

tensor([[0.8412, 1.9546, 2.9964],
        [3.9999, 5.0000, 6.0000]])

In [12]:
#import torch tensors
import torch.nn.functional as F
F.gelu(example_tensor ,approximate="tanh")

tensor([[0.8412, 1.9546, 2.9964],
        [3.9999, 5.0000, 6.0000]])

In [13]:
class UstaMLP(nn.Module):
    def __init__(self,embedding_dim ,hidden_dim):
        super().__init__()

        self.gate_proj = nn.Linear(embedding_dim,hidden_dim)
        self.up_proj = nn.Linear(embedding_dim,hidden_dim)
        self_down_proj = nn.Linear(hidden_dim,embedding_dim)
        self.gelu = GELU

    def forward(self,x):
        gate = self.gate_proj(x)
        up = self.gelu(gate)
        fuse = gate * up
        outputs = self.down_proj(fuse)
        return outputs


In [14]:
import torch
import torch.nn as nn

from usta_multi_head_attention import UstaMultiHeadAttention
from usta_layer_norm import UstaLayerNorm
from usta_mlp import UstaMLP


class UstaDecoderBlock(nn.Module):
    def __init__(self, embedding_dim, num_heads, context_length):
        super().__init__()

        self.self_attention = UstaMultiHeadAttention(
            embedding_dim,
            embedding_dim,
            context_length,
            num_heads,
            dropout_rate=0.5
        )
        self.norm1 = UstaLayerNorm(embedding_dim)
        self.mlp = UstaMLP(embedding_dim, embedding_dim)
        self.norm2 = UstaLayerNorm(embedding_dim)

    def forward(self, x):
        res = self.norm1(x)

       
        x = self.self_attention(x)

        x = self.norm1(x)

        x = x + res

        res = self.norm2(x)
        x = self.mlp(x)
        x = self.norm2(x)

        x = x + res

        return x


example_tensor = torch.tensor(
    [[1, 2, 3, 4],
     [5, 6, 7, 8]],
    dtype=torch.float32
)

decoder_block = UstaDecoderBlock(
    embedding_dim=4,
    num_heads=2,
    context_length=4
)


output = decoder_block(example_tensor)
print(output)

tensor([[-1.6882, -0.4778,  0.9498,  1.2161],
        [-1.8425, -0.3835,  1.0552,  1.1707]], grad_fn=<AddBackward0>)
