In [2]:
import torch
from usta_model import UstaModel
from usta_tokenizer import UstaTokenizer

u_tokenizer = UstaTokenizer("tokenizer.json")

prompt = "Artificial is intelligence is transforming the way people the interact with technology"
tokens = u_tokenizer.encode(prompt)

torch.manual_seed(1)
u_model = UstaModel(vocab_size=len(u_tokenizer.vocab),embedding_dim = 4,context_length= 23)

sentence_meanings_with_attention_context = u_model(tokens)
sentence_meanings_with_attention_context

tensor([[ 0.0397, -0.1072,  0.2113,  0.1237],
        [ 0.4847,  0.1908,  0.4622,  0.1433],
        [ 0.0159, -0.4085,  0.2729,  0.2234],
        [-0.2753, -0.2668,  0.0404,  0.0961],
        [-0.1152, -0.2378,  0.1358,  0.1335],
        [-0.3386, -0.1683, -0.0024,  0.0619],
        [-0.0300, -0.2767,  0.2136,  0.1748],
        [ 0.2600,  0.0322,  0.3668,  0.1439],
        [-0.4278, -0.5084, -0.0202,  0.1493],
        [-0.3572, -0.3952,  0.0286,  0.1236],
        [ 0.0746, -0.2527,  0.2640,  0.1823],
        [-0.5943, -0.4019, -0.1142,  0.0814],
        [-0.2917, -0.2151,  0.0300,  0.0811],
        [ 0.0229, -0.2071,  0.2747,  0.1695],
        [-0.2046, -0.2895,  0.0931,  0.1290],
        [-0.3811, -0.5295,  0.0481,  0.1672],
        [ 0.1124, -0.1837,  0.2801,  0.1693],
        [-0.7151, -0.5491, -0.1738,  0.1015],
        [-0.4978, -0.5368, -0.0607,  0.1397],
        [-0.1478, -0.4161,  0.2041,  0.2008],
        [-0.1813, -0.4048,  0.1384,  0.1767],
        [-0.3247, -0.6460,  0.1125

In [4]:
from transformers import Gemma3ForCausalLM
gemma_model = Gemma3ForCausalLM.from_pretrained("google/gemma-3-1b-it")
u_model ,gemma_model

Loading weights: 100%|██████████| 340/340 [00:00<00:00, 4858.95it/s]


(UstaModel(
   (embedding): Embedding(65, 4)
   (pos_embedding): Embedding(23, 4)
   (self_attention): UstaSelfAttention(
     (q_weights): Linear(in_features=4, out_features=4, bias=False)
     (k_weights): Linear(in_features=4, out_features=4, bias=False)
     (v_weights): Linear(in_features=4, out_features=4, bias=False)
   )
 ),
 Gemma3ForCausalLM(
   (model): Gemma3TextModel(
     (embed_tokens): Gemma3TextScaledWordEmbedding(262144, 1152, padding_idx=0)
     (layers): ModuleList(
       (0-25): 26 x Gemma3DecoderLayer(
         (self_attn): Gemma3Attention(
           (q_proj): Linear(in_features=1152, out_features=1024, bias=False)
           (k_proj): Linear(in_features=1152, out_features=256, bias=False)
           (v_proj): Linear(in_features=1152, out_features=256, bias=False)
           (o_proj): Linear(in_features=1024, out_features=1152, bias=False)
           (q_norm): Gemma3RMSNorm((256,), eps=1e-06)
           (k_norm): Gemma3RMSNorm((256,), eps=1e-06)
         )
     

In [3]:
u_tokenizer.tokenize(prompt)

['artificial',
 ' ',
 'is',
 ' ',
 'intelligence',
 ' ',
 'is',
 ' ',
 'transforming',
 ' ',
 'the',
 ' ',
 'way',
 ' ',
 'people',
 ' ',
 'the',
 ' ',
 'interact',
 ' ',
 'with',
 ' ',
 'technology']

In [4]:
from plot_tokens import plot_tokens 

u_sentences = [
    {
        "words" : sentence_meanings.detach().numpy(),
        "labels" : u_tokenizer.tokenize(prompt),
        "color" : "red"
    }
]
plot_tokens(u_sentences ,"Models Context Space")

In [5]:
sentence_meanings

tensor([[-0.1002, -0.6092, -0.9798, -1.6091],
        [-2.1008,  0.6499, -0.2940, -2.5011],
        [-1.4416, -0.9042,  0.1310,  0.5037],
        [ 0.2833, -2.1807,  0.2088, -2.5096],
        [ 0.6953,  0.3404, -0.6180, -0.5343],
        [ 1.8650,  1.1651,  0.7032, -2.4181],
        [ 0.2580,  1.6820, -0.0755,  0.5149],
        [-1.8355,  1.2110,  1.1696, -2.2302],
        [ 1.2498, -0.5207,  0.3446,  0.6405],
        [-0.3373, -2.1730,  1.5894, -1.9534],
        [-0.5934, -0.6760, -1.0375, -0.1216],
        [ 2.1163,  0.5976,  1.9458, -1.5987],
        [ 0.8353, -0.7396,  0.5345, -2.6171],
        [-1.4241,  1.6756,  2.2246, -1.1803],
        [ 0.6203, -0.0239, -0.0059, -0.8088],
        [-0.9310, -1.9922,  2.4147, -0.7148],
        [-0.7587, -0.4833, -0.7876, -0.6862],
        [ 2.1989, -0.0175,  2.5086, -0.2208],
        [ 1.1868, -1.4590,  0.7174,  0.3294],
        [-0.8991,  2.0068,  2.5025,  0.2820],
        [ 0.0395,  0.2004,  0.3689,  0.3370],
        [-1.4506, -1.6527,  2.3966

In [6]:
artificial_pos = [-0.1002, -0.6092, -0.9798, -1.6091]
is_pos = [-2.1008,  0.6499, -0.2940, -2.5011]

In [7]:
hardness_dist = artificial_pos[0] - is_pos[0]
brightness_dist = artificial_pos[1] - is_pos[1]
redness_dist = artificial_pos[2] - is_pos[2]
blueness_dist = artificial_pos[3] - is_pos[3]
hardness_dist , brightness_dist ,redness_dist ,blueness_dist

(2.0006, -1.2591, -0.6858, 0.8920000000000001)

In [8]:
cos_sim_hardness = artificial_pos[0] * is_pos[0]
cos_sim_brightness = artificial_pos[1] * is_pos[1]
cos_sim_redness = artificial_pos[2] * is_pos[2]
cos_sim_blueness = artificial_pos[3] * is_pos[3]

total_cos_sim = cos_sim_hardness + cos_sim_brightness + cos_sim_redness + cos_sim_blueness
cos_sim_blueness, cos_sim_brightness ,cos_sim_hardness , cos_sim_redness ,total_cos_sim

(4.02452001, -0.39591908, 0.21050016, 0.28806119999999996, 4.127162289999999)

In [9]:
total_dist = hardness_dist + brightness_dist + redness_dist + blueness_dist
total_dist

0.9477

In [10]:
sentence_meanings[0] , sentence_meanings[1],sentence_meanings[2],sentence_meanings[3]

(tensor([-0.1002, -0.6092, -0.9798, -1.6091], grad_fn=<SelectBackward0>),
 tensor([-2.1008,  0.6499, -0.2940, -2.5011], grad_fn=<SelectBackward0>),
 tensor([-1.4416, -0.9042,  0.1310,  0.5037], grad_fn=<SelectBackward0>),
 tensor([ 0.2833, -2.1807,  0.2088, -2.5096], grad_fn=<SelectBackward0>))

In [11]:
artificial_similarities = []

for i in range(sentence_meanings.shape[0]):
    cs_artificial_i = sentence_meanings[0][0] * sentence_meanings[i][0] + sentence_meanings[0][1] * sentence_meanings[i][1] + sentence_meanings[0][2] * sentence_meanings[i][2] + sentence_meanings[0][3] * sentence_meanings[i][3]
    artificial_similarities.append(cs_artificial_i)

artificial_similarities

[tensor(3.9303, grad_fn=<AddBackward0>),
 tensor(4.1271, grad_fn=<AddBackward0>),
 tensor(-0.2436, grad_fn=<AddBackward0>),
 tensor(5.1338, grad_fn=<AddBackward0>),
 tensor(1.1882, grad_fn=<AddBackward0>),
 tensor(2.3055, grad_fn=<AddBackward0>),
 tensor(-1.8051, grad_fn=<AddBackward0>),
 tensor(1.8888, grad_fn=<AddBackward0>),
 tensor(-1.1763, grad_fn=<AddBackward0>),
 tensor(2.9436, grad_fn=<AddBackward0>),
 tensor(1.6835, grad_fn=<AddBackward0>),
 tensor(0.0901, grad_fn=<AddBackward0>),
 tensor(4.0544, grad_fn=<AddBackward0>),
 tensor(-1.1586, grad_fn=<AddBackward0>),
 tensor(1.2597, grad_fn=<AddBackward0>),
 tensor(0.0912, grad_fn=<AddBackward0>),
 tensor(2.2463, grad_fn=<AddBackward0>),
 tensor(-2.3121, grad_fn=<AddBackward0>),
 tensor(-0.4629, grad_fn=<AddBackward0>),
 tensor(-4.0380, grad_fn=<AddBackward0>),
 tensor(-1.0298, grad_fn=<AddBackward0>),
 tensor(-2.4407, grad_fn=<AddBackward0>),
 tensor(0.2306, grad_fn=<AddBackward0>)]

In [12]:
#all similarities 
all_similarities = torch.zeros(sentence_meanings.shape[0],sentence_meanings.shape[0])

for j in range(sentence_meanings.shape[0]):
    j_similarities = torch.zeros(sentence_meanings.shape[0])
    
    for i in range(sentence_meanings.shape[0]):
        for k in range(sentence_meanings.shape[1]):
            cs_j_i = sentence_meanings[j][k] * sentence_meanings[i][k]
            j_similarities[i] += cs_j_i
    
    all_similarities[j] = j_similarities

all_similarities.detach().numpy()

array([[ 3.93028927e+00,  4.12705517e+00, -2.43584871e-01,
         5.13377285e+00,  1.18824553e+00,  2.30545449e+00,
        -1.80509889e+00,  1.88884521e+00, -1.17626393e+00,
         2.94355440e+00,  1.68349719e+00,  9.00509357e-02,
         4.05437756e+00, -1.15855300e+00,  1.25971925e+00,
         9.11583900e-02,  2.24625111e+00, -2.31214476e+00,
        -4.62941408e-01, -4.03804111e+00, -1.02976739e+00,
        -2.44065619e+00,  2.30617419e-01],
       [ 4.12705517e+00,  1.11775875e+01,  1.14257348e+00,
         4.20313311e+00,  2.78488755e-01,  2.68046713e+00,
        -7.14565575e-01,  9.87727928e+00, -4.66728020e+00,
         3.71485496e+00,  1.41650677e+00, -6.30938292e-01,
         4.15311623e+00,  6.37864780e+00,  7.06049442e-01,
         1.73913324e+00,  3.22752237e+00, -4.81611872e+00,
        -4.47606850e+00,  1.75218868e+00, -9.04172421e-01,
        -6.65808439e-01, -1.85600847e-01],
       [-2.43584871e-01,  1.14257348e+00,  3.16661692e+00,
         3.26618910e-01, -1.6

In [13]:
all_similarities.shape

torch.Size([23, 23])

In [14]:
sentence_meanings , sentence_meanings.T

(tensor([[-0.1002, -0.6092, -0.9798, -1.6091],
         [-2.1008,  0.6499, -0.2940, -2.5011],
         [-1.4416, -0.9042,  0.1310,  0.5037],
         [ 0.2833, -2.1807,  0.2088, -2.5096],
         [ 0.6953,  0.3404, -0.6180, -0.5343],
         [ 1.8650,  1.1651,  0.7032, -2.4181],
         [ 0.2580,  1.6820, -0.0755,  0.5149],
         [-1.8355,  1.2110,  1.1696, -2.2302],
         [ 1.2498, -0.5207,  0.3446,  0.6405],
         [-0.3373, -2.1730,  1.5894, -1.9534],
         [-0.5934, -0.6760, -1.0375, -0.1216],
         [ 2.1163,  0.5976,  1.9458, -1.5987],
         [ 0.8353, -0.7396,  0.5345, -2.6171],
         [-1.4241,  1.6756,  2.2246, -1.1803],
         [ 0.6203, -0.0239, -0.0059, -0.8088],
         [-0.9310, -1.9922,  2.4147, -0.7148],
         [-0.7587, -0.4833, -0.7876, -0.6862],
         [ 2.1989, -0.0175,  2.5086, -0.2208],
         [ 1.1868, -1.4590,  0.7174,  0.3294],
         [-0.8991,  2.0068,  2.5025,  0.2820],
         [ 0.0395,  0.2004,  0.3689,  0.3370],
         [-1.

In [15]:
sentence_meanings.shape , sentence_meanings.T.shape

(torch.Size([23, 4]), torch.Size([4, 23]))

In [16]:
# Yukarıda yaptığımız işlemin daha kısa şekilde torch kütüphanesi ile yapılışı
#Query , Key ,Value
all_sim_torch = sentence_meanings @ sentence_meanings.T
all_sim_torch.detach().numpy()

array([[ 3.93028927e+00,  4.12705517e+00, -2.43584871e-01,
         5.13377285e+00,  1.18824553e+00,  2.30545449e+00,
        -1.80509889e+00,  1.88884532e+00, -1.17626393e+00,
         2.94355440e+00,  1.68349719e+00,  9.00511816e-02,
         4.05437756e+00, -1.15855324e+00,  1.25971925e+00,
         9.11583155e-02,  2.24625087e+00, -2.31214476e+00,
        -4.62941378e-01, -4.03804064e+00, -1.02976739e+00,
        -2.44065595e+00,  2.30617404e-01],
       [ 4.12705517e+00,  1.11775875e+01,  1.14257348e+00,
         4.20313311e+00,  2.78488785e-01,  2.68046689e+00,
        -7.14565456e-01,  9.87727833e+00, -4.66728020e+00,
         3.71485472e+00,  1.41650665e+00, -6.30938232e-01,
         4.15311623e+00,  6.37864780e+00,  7.06049442e-01,
         1.73913312e+00,  3.22752237e+00, -4.81611872e+00,
        -4.47606802e+00,  1.75218868e+00, -9.04172421e-01,
        -6.65808499e-01, -1.85600847e-01],
       [-2.43584871e-01,  1.14257348e+00,  3.16661692e+00,
         3.26618910e-01, -1.6

In [17]:
torch.sum(all_sim_torch[0])

tensor(16.5058, grad_fn=<SumBackward0>)

In [18]:
attention_weights = torch.softmax(all_similarities ,dim = 1)
attention_weights

tensor([[1.2614e-01, 1.5357e-01, 1.9416e-03, 4.2025e-01, 8.1282e-03, 2.4842e-02,
         4.0738e-04, 1.6378e-02, 7.6401e-04, 4.7023e-02, 1.3338e-02, 2.7105e-03,
         1.4280e-01, 7.7766e-04, 8.7304e-03, 2.7135e-03, 2.3414e-02, 2.4535e-04,
         1.5592e-03, 4.3676e-05, 8.8455e-04, 2.1576e-04, 3.1196e-03],
        [6.7474e-04, 7.7830e-01, 3.4119e-05, 7.2808e-04, 1.4379e-05, 1.5882e-04,
         5.3266e-06, 2.1205e-01, 1.0228e-07, 4.4681e-04, 4.4871e-05, 5.7912e-06,
         6.9256e-04, 6.4120e-03, 2.2050e-05, 6.1955e-05, 2.7446e-04, 8.8139e-08,
         1.2384e-07, 6.2769e-05, 4.4066e-06, 5.5927e-06, 9.0401e-06],
        [5.4363e-03, 2.1742e-02, 1.6457e-01, 9.6148e-03, 1.3184e-03, 5.3330e-05,
         1.3409e-03, 1.2399e-02, 2.6472e-03, 3.7040e-02, 2.4687e-02, 1.1027e-04,
         1.1655e-03, 8.7700e-03, 1.9268e-03, 1.5392e-01, 2.0462e-02, 3.6784e-04,
         6.0793e-03, 6.6069e-03, 6.7980e-03, 5.0559e-01, 7.3608e-03],
        [1.7479e-03, 6.8921e-04, 1.4283e-05, 7.3675e-01, 2.00

In [19]:
torch.sum(attention_weights[0])

tensor(1.0000, grad_fn=<SumBackward0>)

In [20]:
sentence_context_vector = attention_weights @ sentence_meanings #Value
sentence_context_vector , sentence_meanings

(tensor([[-0.1083, -1.0775,  0.0864, -2.2379],
         [-2.0329,  0.7698,  0.0342, -2.4333],
         [-1.2251, -1.3744,  1.6724,  0.1513],
         [ 0.1794, -2.0933,  0.5152, -2.3891],
         [ 0.8722,  0.2323,  0.4111, -1.5279],
         [ 1.8943,  1.0027,  0.9708, -2.2352],
         [-0.1575,  1.5065,  1.1448, -0.0600],
         [-1.7991,  1.1932,  1.1050, -2.0797],
         [ 1.4802, -0.3777,  1.4966, -0.2359],
         [-0.3219, -2.1147,  1.4827, -1.8285],
         [-0.5392, -0.6527, -0.2594, -1.0138],
         [ 2.0719,  0.5787,  1.8169, -1.5065],
         [ 0.6602, -1.1189,  0.6248, -2.4019],
         [-1.4032,  1.6416,  2.0743, -1.1147],
         [ 0.9530, -0.0891,  0.7957, -1.7975],
         [-0.9088, -1.9588,  2.2529, -0.6815],
         [-0.8684, -0.3879, -0.0704, -1.7317],
         [ 2.1703,  0.1176,  2.3736, -0.5281],
         [ 0.9269, -1.0071,  1.5603, -0.4730],
         [-1.0129,  1.9256,  2.4335, -0.0458],
         [-0.0114,  0.1865,  1.2759, -0.3844],
         [-1.

In [21]:
sentence_meanings_without_pos = u_model.embedding(tokens)

In [22]:
u_sentences = [
    {
        "words" : sentence_meanings_without_pos.detach().numpy(),
        "labels" : u_tokenizer.tokenize(prompt),
        "color" : "blue",
    },
    {
        "words" : sentence_meanings.detach().numpy(),
        "labels" : u_tokenizer.tokenize(prompt),
        "color" : "purple",
    }, 
    {
        "words" : sentence_context_vector.detach().numpy(),
        "labels" : u_tokenizer.tokenize(prompt),
        "color" : "orange",
    },
]
plot_tokens(u_sentences ,"Models Attention Sentence Space")

![image.png](https://lena-voita.github.io/resources/lectures/seq2seq/transformer/qkv_attention_formula-min.png)


In [ ]:
q_weights = torch.nn.Linear(4,3 , bias= False)
k_weights = torch.nn.Linear(4,3 , bias= False)
v_weights = torch.nn.Linear(4,3 , bias= False)

q_of_sentence = q_weights(sentence_meanings_with_attention_context)
k_of_sentence = k_weights(sentence_meanings_with_attention_context)
v_of_sentence = v_weights(sentence_meanings_with_attention_context)

q_of_sentence.shape ,k_of_sentence.shape ,v_of_sentence.shape

(torch.Size([23, 3]), torch.Size([23, 3]), torch.Size([23, 3]))

In [38]:
attention_scores = q_of_sentence @ k_of_sentence.T
attention_weights = torch.softmax(attention_scores / k_of_sentence.shape[-1] ** 0.5 , dim = 1)

context_vector = attention_weights @ v_of_sentence
context_vector

tensor([[ 0.1055,  0.2626,  0.3606],
        [ 0.1582,  0.1751,  0.2546],
        [ 0.2427,  0.0331,  0.5918],
        [ 0.2388,  0.2069,  0.4237],
        [ 0.0482,  0.2799,  0.4590],
        [-0.0177,  0.3853,  0.3492],
        [ 0.0481,  0.2040,  0.5508],
        [ 0.1879,  0.1278,  0.3289],
        [ 0.1350,  0.1709,  0.7008],
        [ 0.3471,  0.0968,  0.5429],
        [ 0.1416,  0.1768,  0.4781],
        [ 0.0974,  0.2752,  0.5375],
        [ 0.1421,  0.2681,  0.3867],
        [ 0.2045,  0.0649,  0.4661],
        [ 0.1035,  0.2405,  0.4843],
        [ 0.3893, -0.0273,  0.6842],
        [ 0.1477,  0.1822,  0.4304],
        [ 0.1758,  0.1535,  0.7638],
        [ 0.2038,  0.1356,  0.7234],
        [ 0.1978,  0.0130,  0.6312],
        [ 0.1487,  0.1343,  0.6057],
        [ 0.3846, -0.1312,  0.7913],
        [ 0.1542,  0.1627,  0.5617]], grad_fn=<MmBackward0>)

In [44]:
from plot_tokens import plot_tokens
u_sentences = [
    {
        "words" : q_of_sentence.detach().numpy(),
        "labels" : u_tokenizer.tokenize(prompt),
        "color" : "blue",
    },
    {
        "words" : k_of_sentence.detach().numpy(),
        "labels" : u_tokenizer.tokenize(prompt),
        "color" : "purple",
    }, 
    {
        "words" : v_of_sentence.detach().numpy(),
        "labels" : u_tokenizer.tokenize(prompt),
        "color" : "orange",
    },
    {
        "words" : context_vector.detach().numpy(),
        "labels" : u_tokenizer.tokenize(prompt),
        "color" : "green",
    },
]
plot_tokens(u_sentences ,"Query, Key , Value and Context Vector Space")