In [1]:
import torch
from usta_model import UstaModel
from usta_tokenizer import UstaTokenizer

u_tokenizer = UstaTokenizer("tokenizer.json")

prompt = "Artificial is intelligence is transforming the way people the interact with technology"
tokens = u_tokenizer.encode(prompt)

tokens

tensor([ 1, 63,  3, 63,  2, 63,  3, 63,  4, 63,  5, 63,  6, 63,  7, 63,  5, 63,
         8, 63,  9, 63, 10])

In [2]:
torch.manual_seed(1)
u_model = UstaModel(vocab_size=len(u_tokenizer.vocab),embedding_dim = 4,num_heads = 2,context_length= 23,num_layers = 3)

out = u_model(tokens)
out.shape

torch.Size([23, 65])

In [3]:
u_model

UstaModel(
  (embedding): Embedding(65, 4)
  (pos_embedding): Embedding(23, 4)
  (layers): Sequential(
    (0): UstaDecoderBlock(
      (self_attention): UstaMultiHeadAttention(
        (multi_head_attention): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=4, out_features=4, bias=True)
        )
        (projection): Linear(in_features=4, out_features=4, bias=True)
      )
      (norm1): UstaLayerNorm()
      (mlp): UstaMLP(
        (gate_proj): Linear(in_features=4, out_features=4, bias=True)
        (up_proj): Linear(in_features=4, out_features=4, bias=True)
        (down_proj): Linear(in_features=4, out_features=4, bias=True)
        (gelu): GELU()
      )
      (norm2): UstaLayerNorm()
    )
    (1): UstaDecoderBlock(
      (self_attention): UstaMultiHeadAttention(
        (multi_head_attention): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=4, out_features=4, bias=True)
        )
        (projection): L

In [4]:
import torch 

probs = torch.softmax(out[0] , dim =-1)
max_prob ,max_index = torch.max(probs,dim =-1)
max_prob , max_index , probs

(tensor(0.1537, grad_fn=<MaxBackward0>),
 tensor(60),
 tensor([0.0429, 0.0363, 0.0060, 0.0025, 0.0019, 0.0018, 0.0241, 0.0129, 0.0017,
         0.0049, 0.0015, 0.0064, 0.0094, 0.0462, 0.0085, 0.0227, 0.0016, 0.0133,
         0.0231, 0.0054, 0.0298, 0.0079, 0.0012, 0.0030, 0.0161, 0.0036, 0.0046,
         0.0152, 0.0391, 0.0007, 0.0273, 0.0022, 0.0039, 0.0049, 0.0048, 0.0106,
         0.0095, 0.0159, 0.0125, 0.0227, 0.0441, 0.0040, 0.0124, 0.0099, 0.0086,
         0.0984, 0.0013, 0.0069, 0.0296, 0.0103, 0.0151, 0.0080, 0.0067, 0.0161,
         0.0115, 0.0044, 0.0062, 0.0037, 0.0010, 0.0197, 0.1537, 0.0038, 0.0046,
         0.0108, 0.0005], grad_fn=<SoftmaxBackward0>))

In [ ]:
from transformers import AutoTokenizer , AutoModelForCausalLM

q_tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen3-0.6B")
q_model= AutoModelForCausalLM.from_pretrained("Qwen/Qwen3-0.6B")

In [ ]:
q_tokens = q_tokenizer.encode(prompt)
q_tokens

[9286, 16488, 374, 11229, 374, 45790, 279, 1616, 1251, 279, 16282, 448, 5440]

In [ ]:
q_model.generate(torch.tensor([q_tokens]))

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/transformers/generation/utils.py:1638: UserWarning: Using the model-agnostic default `max_length` (=33) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


tensor([[ 9286, 16488,   374, 11229,   374, 45790,   279,  1616,  1251,   279,
         16282,   448,  5440,    11,   323,   419,   702,  6069,   311,   264,
          2696,   315,  4344,   304,   279,  1616,  1251,   990,  5440,    13,
         15920,   315,   279]])

In [ ]:
q_out = q_model(torch.tensor([q_tokens]))
q_out

CausalLMOutputWithPast(loss=None, logits=tensor([[[ 4.7812,  4.8125,  5.1562,  ...,  2.0000,  2.0000,  2.0000],
         [ 6.0938,  9.1875,  4.3125,  ..., -1.4141, -1.4141, -1.4141],
         [ 7.2188,  6.7812,  4.4688,  ..., -0.6875, -0.6875, -0.6875],
         ...,
         [ 9.8125,  7.9062,  6.2812,  ..., -0.4258, -0.4258, -0.4258],
         [ 7.0938,  7.5000,  2.0469,  ..., -1.7266, -1.7266, -1.7266],
         [10.8125,  8.8125,  5.3438,  ..., -1.5234, -1.5234, -1.5234]]],
       dtype=torch.bfloat16, grad_fn=<UnsafeViewBackward0>), past_key_values=DynamicCache(layers=[DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer]), hidden_states=None, atten

In [ ]:
q_out.logits[0,0,:].shape

torch.Size([151936])

In [ ]:
probs = torch.softmax(q_out.logits[0,1,:] , dim =-1)
max_prob ,max_index = torch.max(probs,dim =-1)
max_prob , max_index , probs

(tensor(0.6875, dtype=torch.bfloat16, grad_fn=<MaxBackward0>),
 tensor(21392),
 tensor([1.9372e-06, 4.2677e-05, 3.2596e-07,  ..., 1.0623e-09, 1.0623e-09,
         1.0623e-09], dtype=torch.bfloat16, grad_fn=<SoftmaxBackward0>))

In [ ]:
q_tokenizer.decode([max_index])

' Intelligence'

In [ ]:
!hf auth login

Hint: A new version of huggingface_hub (1.24.0) is available! You are using version 1.23.0.
To update, run: hf update
User is already logged in. Use `hf auth login --force` to force re-login.
