In [1]:
from transformers import PreTrainedTokenizerFast
from tokenizers import normalizers

# 1. Hugging Face'teki mevcut tokenizer'ını çekiyoruz
tokenizer = PreTrainedTokenizerFast.from_pretrained("serratanis/hf_tokenizer")

# 2. Arka planda çalışan çekirdek tokenizer nesnesine ulaşıyoruz
backend_tokenizer = tokenizer.backend_tokenizer

# 3. Kural Setini Gömüyoruz (Normalizer)
# Artık tokenizer her metni gördüğünde ÖNCE küçük harfe çevirecek, SONRA nokta ve virgülleri silecektir.
backend_tokenizer.normalizer = normalizers.Sequence([
    normalizers.Lowercase(),
    normalizers.Replace(".", " "),
    normalizers.Replace(",", " ")
])

# 4. Bu yeni, akıllı tokenizer'ı Hugging Face repona üzerine yazarak güncelliyoruz
tokenizer.push_to_hub("serratanis/hf_tokenizer")

print("Tokenizer başarıyla güncellendi ve normalizer eklendi!")

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
No files have been modified since last commit. Skipping to prevent empty commit.


Tokenizer başarıyla güncellendi ve normalizer eklendi!


In [2]:
text1 = "The cat chased the dog"
text2 = "The dog chased the cat"

text = "The capital of France is"

In [3]:
from tokenizers import Tokenizer
from tokenizers.models import BPE
from tokenizers.trainers import BpeTrainer
from tokenizers.pre_tokenizers import Whitespace

In [4]:
hf_tokenizer = Tokenizer(BPE())

In [5]:
hf_tokenizer.get_vocab_size()

0

In [6]:
hf_tokenizer.pre_tokenizer = Whitespace()

In [7]:
trainer = BpeTrainer(vocab_size = 64, special_tokens=["<unk>"])

hf_tokenizer.train(["text.txt"],trainer)

In [8]:
hf_tokenizer.get_vocab_size(),hf_tokenizer.encode(text1).ids

(64, [10, 19, 16, 14, 42, 14, 19, 12, 29, 54, 53, 15, 25, 18])

In [9]:
hf_tokenizer.save("hf_tokenizer.json")

In [10]:
from transformers import PreTrainedTokenizerFast

fast_tokenizer = PreTrainedTokenizerFast(tokenizer_file = "hf_tokenizer.json")

fast_tokenizer.encode(text1)

[10, 19, 16, 14, 42, 14, 19, 12, 29, 54, 53, 15, 25, 18]

In [11]:
!hf auth login

User is already logged in. Use `hf auth login --force` to force re-login.


In [12]:
!hf update

Current version: 1.23.0
Checking for updates to latest version...
hf is up to date (1.23.0)


In [13]:
fast_tokenizer.push_to_hub("serratanis/hf_tokenizer")

CommitInfo(commit_url='https://huggingface.co/serratanis/hf_tokenizer/commit/9b2950672792be7c1ed84713998f19ac3eaf56ea', commit_message='Upload tokenizer', commit_description='', oid='9b2950672792be7c1ed84713998f19ac3eaf56ea', pr_url=None, repo_url=RepoUrl('https://huggingface.co/serratanis/hf_tokenizer', endpoint='https://huggingface.co', repo_type='model', repo_id='serratanis/hf_tokenizer'), pr_revision=None, pr_num=None)

In [14]:
prompt= "Better datasets usually produce better language models because they contain richer linguistic patterns. "
next_token = " "
output = "Better datasets usually produce better language models because they contain richer linguistic patterns."

In [15]:
data = "Better datasets usually produce better language models because they contain richer linguistic patterns."
hedef = "datasets usually produce better language models because they contain richer linguistic patterns."

In [16]:
from transformers import PreTrainedTokenizerFast

# Hatalı olan yerel dosya yerine, doğrudan kendi sağlam repodan çekiyoruz
tokenizer = PreTrainedTokenizerFast.from_pretrained("serratanis/hf_tokenizer")

data = "Better datasets usually produce better language models because they contain richer linguistic patterns."

ids = tokenizer.encode(data)
print("Uzunluk:", len(ids))
print("ID'ler:", ids)

Uzunluk: 66
ID'ler: [3, 50, 57, 15, 42, 12, 29, 50, 29, 31, 29, 31, 44, 22, 35, 26, 49, 15, 31, 14, 16, 13, 50, 57, 22, 45, 18, 31, 12, 59, 23, 25, 15, 55, 29, 13, 16, 14, 12, 31, 29, 16, 53, 35, 14, 40, 30, 12, 37, 28, 51, 19, 39, 22, 43, 31, 20, 29, 30, 51, 26, 42, 57, 24, 29, 1]


In [17]:
ids = tokenizer.encode(data)

len(ids) ,ids

(66,
 [3,
  50,
  57,
  15,
  42,
  12,
  29,
  50,
  29,
  31,
  29,
  31,
  44,
  22,
  35,
  26,
  49,
  15,
  31,
  14,
  16,
  13,
  50,
  57,
  22,
  45,
  18,
  31,
  12,
  59,
  23,
  25,
  15,
  55,
  29,
  13,
  16,
  14,
  12,
  31,
  29,
  16,
  53,
  35,
  14,
  40,
  30,
  12,
  37,
  28,
  51,
  19,
  39,
  22,
  43,
  31,
  20,
  29,
  30,
  51,
  26,
  42,
  57,
  24,
  29,
  1])

In [3]:
context_length = 32

In [19]:
import json

with open("tokenizer.json", "r") as f:
    vocab = json.load(f)

print(" " in vocab)
print(vocab.keys())

False
dict_keys(['version', 'vocab'])


In [20]:
from usta_tokenizer import UstaTokenizer

tokenizer = UstaTokenizer("tokenizer.json")

ids =  tokenizer.encode(prompt)

ids, tokenizer.decode(ids)

(tensor([ 0,  0,  0,  0,  0,  0, 63, 31, 63,  0,  0,  0,  0,  0,  0,  0, 63,  0,
          0,  0,  0,  0,  0,  0, 63,  0,  0,  0,  0,  0,  0, 63, 12, 63, 13, 63,
          0,  0,  0,  0,  0,  0,  0, 63,  5,  0, 63,  0, 23,  0,  0,  0,  0, 63,
          0,  0,  0,  0,  0,  0, 63,  0,  0,  0,  0,  0,  3,  0,  0,  0, 63, 15,
          0]),
 '<unk><unk><unk><unk><unk><unk> datasets <unk><unk><unk><unk><unk><unk><unk> <unk><unk><unk><unk><unk><unk><unk> <unk><unk><unk><unk><unk><unk> language models <unk><unk><unk><unk><unk><unk><unk> the<unk> <unk>on<unk><unk><unk><unk> <unk><unk><unk><unk><unk><unk> <unk><unk><unk><unk><unk>is<unk><unk><unk> patterns<unk>')

In [21]:
from huggingface_hub import whoami
print(whoami())

{'type': 'user', 'id': '6a44ee77ea1b678c9ba584ef', 'name': 'serratanis', 'fullname': 'Serra Tanış', 'canPay': False, 'billingMode': 'prepaid', 'periodEnd': 1785542400, 'isPro': False, 'avatarUrl': 'https://cdn-avatars.huggingface.co/v1/production/uploads/noauth/JIl7GWb1lxbw2TkWe92Wu.png', 'orgs': [], 'auth': {'type': 'oauth', 'expiresAt': '2026-08-08T06:32:09.000Z'}}


In [22]:
from usta_tokenizer import UstaTokenizer

my_tokenizer = UstaTokenizer("tokenizer.json")

token_ids = my_tokenizer.encode(text)

In [23]:
girdi = "Artificial intelligence is transforming the way people interact with"
cikti = "intelligence is transforming the way people interact with technology"


In [24]:
with open ("text.txt","r") as f:
    text = f.read()

text

'Artificial intelligence is transforming the way people interact with technology. Large language models learn patterns from text and generate meaningful responses based on context. Machine learning algorithms improve through training on diverse datasets. Neural networks consist of multiple layers that process information efficiently. Natural language processing enables computers to understand human language. Tokenization converts text into smaller units called tokens. Each token receives a unique numerical identifier from the vocabulary. Unknown words are replaced with a special unknown token. Padding tokens are added to sequences so they have equal length during training. The model predicts the next token by learning relationships between previous tokens. During optimization the loss function measures prediction errors and gradient descent updates the model parameters. Better datasets usually produce better language models because they contain richer linguistic patterns.Artificial int

In [25]:
token_ids=tokenizer.encode(text)

ids_text = ""
for token_id in token_ids:
    ids_text += f"{token_ids}"
with open("token_ids.txt","w") as f :
    f.write(ids_text)

In [26]:
import torch
from torch.utils.data import DataLoader
from text_dataset import TextDataset
stride = 1
context_length = 12
def create_data_loader(token_ids : list,context_length :int ,stride:int ,
                       batch_size:int , shuffle :bool = True , device : str = "cpu"):
    dataset = TextDataset(token_ids,context_length,stride)
    dataloader = DataLoader(
        dataset,
        batch_size =batch_size,
        shuffle=shuffle,
        generator = torch.Generator(device = device))
 
    return dataloader 

    

In [27]:
train_data_loader = create_data_loader(
    token_ids.tolist(),
    context_length,
    stride,
    1
)

In [28]:
with open("/Users/serratanis/Desktop/LLM/text_dataset.py", "r") as f:
    print(f.read())

import torch
from torch.utils.data import DataLoader , Dataset

pad_id = 64

class TextDataset(Dataset):
    def __init__(self,token_ids:list, context_length:int ,stride:int ):
        super().__init__()

        self.inputs = []
        self.targets = []

        for i in range(0,len(token_ids) - context_length,stride):
            input_chunk = token_ids[i  :i+context_length]
            target_chunk = token_ids[i + 1:i+context_length+1]

            #olurda taşma olursa diye traşlama
            input_chunk = input_chunk[:context_length]
            target_chunk = target_chunk[:context_length]

            #eğer az kalırsa da ekleyecek şekilde 
            input_chunk = input_chunk +[pad_id] * (context_length -len(input_chunk))
            target_chunk = target_chunk +[pad_id] * (context_length -len(target_chunk))
            
            input_chunk = input_chunk[:context_length]
            target_chunk = target_chunk[:context_length]         
            self.inputs.append(torch.

In [29]:
with open("/Users/serratanis/Desktop/LLM/text_dataset.py", "r") as f:
    for i, line in enumerate(f, 1):
        print(f"{i:2}: {line.rstrip()}")

 1: import torch
 2: from torch.utils.data import DataLoader , Dataset
 3: 
 4: pad_id = 64
 5: 
 6: class TextDataset(Dataset):
 7:     def __init__(self,token_ids:list, context_length:int ,stride:int ):
 8:         super().__init__()
 9: 
10:         self.inputs = []
11:         self.targets = []
12: 
13:         for i in range(0,len(token_ids) - context_length,stride):
14:             input_chunk = token_ids[i  :i+context_length]
15:             target_chunk = token_ids[i + 1:i+context_length+1]
16: 
17:             #olurda taşma olursa diye traşlama
18:             input_chunk = input_chunk[:context_length]
19:             target_chunk = target_chunk[:context_length]
20: 
21:             #eğer az kalırsa da ekleyecek şekilde
22:             input_chunk = input_chunk +[pad_id] * (context_length -len(input_chunk))
23:             target_chunk = target_chunk +[pad_id] * (context_length -len(target_chunk))
24: 
25:             input_chunk = input_chunk[:context_length]
26:             

In [30]:
import importlib
import text_dataset

importlib.reload(text_dataset)

from text_dataset import TextDataset

In [31]:
dataset = TextDataset(token_ids, 12, 1)

print(len(dataset))
print(dataset[0])

TypeError: unsupported operand type(s) for +: 'Tensor' and 'list'

In [ ]:
import torch
from torch.utils.data import DataLoader
from text_dataset import TextDataset

def create_data_loader(
    token_ids,
    context_length,
    stride,
    batch_size,
    shuffle=True,
    device="cpu",
):
    dataset = TextDataset(token_ids, context_length, stride)

    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
    )

    return dataloader

In [ ]:
train_data_loader = create_data_loader(
    token_ids,
    context_length=12,
    stride=1,
    batch_size=1,
)

In [ ]:
dataset = TextDataset(token_ids, 12, 1)

In [ ]:
from text_dataset import TextDataset

dataset = TextDataset(token_ids, 12, 1)

In [ ]:
token_ids = tokenizer.encode(text)
#save ids

ids_text =""
for token_id in token_ids:
    ids_text += f"{token_id}"

with open("token_ids.txt" ,"w") as f :
    f.write(ids_text)

In [ ]:
import torch
from torch.utils.data import DataLoader
from text_dataset import TextDataset
stride = 1
def create_data_loader(token_ids : list,context_length :int ,stride:int ,
                       batch_size:int , shuffle :bool = True , device : str = "cpu"):
    dataset = TextDataset(token_ids,context_length,stride)
    dataloader = DataLoader(
        dataset,
        batch_size =batch_size,
        shuffle=shuffle,
        generator = torch.Generator(device = device))
 
    return dataloader 

    

In [ ]:
train_data_loader = create_data_loader(token_ids, context_length, stride,1)

len(train_data_loader)

988

In [ ]:
i=0
for batch in enumerate(train_data_loader):
    print(batch)
    i += 1
    if i > 2:
        break

(0, [tensor([[45, 63, 46,  0, 63, 47, 63, 48, 63, 49, 63,  0]]), tensor([[63, 46,  0, 63, 47, 63, 48, 63, 49, 63,  0, 63]])])
(1, [tensor([[63, 27, 63, 28, 63, 29, 63, 30, 63, 23, 63,  0]]), tensor([[27, 63, 28, 63, 29, 63, 30, 63, 23, 63,  0,  0]])])
(2, [tensor([[63, 17, 63, 42, 63, 43, 63, 44, 63, 45, 63, 46]]), tensor([[17, 63, 42, 63, 43, 63, 44, 63, 45, 63, 46,  0]])])


In [ ]:
data_iter = iter(train_data_loader)

In [ ]:
next(data_iter)

[tensor([[51, 63, 52, 63, 16, 63,  5, 63, 53,  0, 63, 54]]),
 tensor([[63, 52, 63, 16, 63,  5, 63, 53,  0, 63, 54, 63]])]

#Embedding yani Sözlük Anlamlarının Sayısal Değerleri

In [ ]:
print(type(token_ids))
print(max(token_ids))

<class 'list'>
63


In [ ]:
# Sadece metni okuyup şifreliyoruz
with open("text.txt", "r", encoding="utf-8") as f: 
    tum_metin = f.read()
token_ids = tokenizer.encode(tum_metin)
# Dataset'e göndermeden hemen önce ne olduğuna bakalım:
print(token_ids[:20])

[1, 63, 2, 63, 3, 63, 4, 63, 5, 63, 6, 63, 7, 63, 8, 63, 9, 63, 10, 0]


## Eng: Embedding is the numerical representation of the dictionary meanings
## Embedding yani Sözlük Anlamlarının Sayısal Değerleri

In [4]:
#elma kelimesinin özelliklerine göre tanımlanması mesela 
artificial_1 = 0.1 #sertlik
artificial_2 = 0.4 #parlaklık
artificial_3 = 0.0 #mavi
artificial_4 = 0.0 #kırmızı #bunlar örnekler 4 boyutlu tanımlıyoruz verileri 

#şu an yaptığımız şey kelimeleri anlamlandırmak
#verdiğimiz değerlerle 

intelligence_1 = 0.0
intelligence_2 = 0.2
intelligence_3 = 0.24
intelligence_4 = 0.3

is_1 = 0.30
is_2 = 0.06
is_3 = 0.03
is_4 = 0.01

transforming_1 = 0.10
transforming_2 = 0.04
transforming_3 = 0.02
transforming_4 = 0.01

In [5]:
dict_v1 =[
 [0.1,0.4,0.0,0.0],
 [0.0,0.2,0.24,0.3],
 [0.30,0.06,0.03,0.01],
 [0.10,0.04,0.02,0.01]
 ]

dict_v1[0]

[0.1, 0.4, 0.0, 0.0]

In [6]:
dict_v2 ={
 "artificial" :[0.1,0.4,0.0,0.0],
 "intelligence" :[0.0,0.2,0.24,0.3],
 "is" :[0.30,0.06,0.03,0.01],
 "transforming" :[0.10,0.04,0.02,0.01]
}
dict_v2["is"] #kelimenin anlamını çağırmış olduk

[0.3, 0.06, 0.03, 0.01]

In [7]:
%pip install plotly

Note: you may need to restart the kernel to use updated packages.


In [8]:
%pip install nbformat

Note: you may need to restart the kernel to use updated packages.


In [9]:
import plotly.graph_objects as go
import plotly.offline

def plot_dots(sentences_data,title):
    data=[
        go.Scatter3d(
            x = sentences_data["words"][:,0],
            y = sentences_data["words"][:,0],
            z = sentences_data["words"][:,0],
            mode="markers+text",
            marker=dict( 
                size = 6,
                color=sentences_data["color"]
            ),
            text=sentence_data["labels"],
            hoverinfo = "text",
        )   for sentence_data in sentences_data
    ]
    layout = go.Layout(
    scene=dict(
        xaxis_title="Sertlik",
        yaxis_title="Parlaklık",
        zaxis_title="Kırmızılık",
    ),
    title=title,
)
data = [
    go.Scatter3d(
        x=[0.1, 0.0, 0.30, 0.10],
        y=[0.4, 0.2, 0.06, 0.04],
        z=[0.0, 0.24, 0.03, 0.02],
        mode="markers+text",
        marker=dict(
            size=10,
            color="red",
        ),
        text=["artificial", "intelligence", "is", "transforming"],  # Virgül eklendi
        hoverinfo="text",
    )
]
layout = go.Layout(
    scene=dict(
        xaxis_title="Sertlik",
        yaxis_title="Parlaklık",
        zaxis_title="Kırmızılık",
    ),
    title="Sözlük V1",
)
fig = go.Figure(data=data, layout=layout)
plotly.offline.iplot(fig)

In [10]:
import plotly.graph_objects as go
import plotly.offline

def plot_dots(sentences_data, title, dims=[0,1,2]):

    data = [
        go.Scatter3d(
            x=sentence_data["words"][:,dims[0]],
            y=sentence_data["words"][:,dims[1]],
            z=sentence_data["words"][:,dims [2]],
            mode="markers+text",
            marker=dict(
                size=6,
                color=sentence_data["color"]
            ),
            text=sentence_data["labels"],
            hoverinfo="text",
        )
        for sentence_data in sentences_data
    ]

    layout = go.Layout(
        scene=dict(
            xaxis_title="X",
            yaxis_title="Y",
            zaxis_title="Z",
        ),
        title=title,
    )

    fig = go.Figure(data=data, layout=layout)
    plotly.offline.iplot(fig)

In [11]:
import numpy as np 

In [9]:
sentences =[
    {
        "words" :np.array([
                [0.1,0.4,0.0,0.0],
                [0.0,0.2,0.24,0.3],
                [0.30,0.06,0.03,0.01],
                [0.10,0.04,0.02,0.01]]),
                "labels" : ["artifical" ,"intelligence","is","transforming"],
                "color" :"blue",
    },
   {
        "words" :np.array([
                [0.0,0.2,0.24,0.3],
                [0.30,0.06,0.03,0.01],
                [0.10,0.04,0.02,0.01]]),
                "labels" : ["intelligence","is","transforming"],
                "color" :"red",
    } 
]

plot_dots(sentences,"Sözlük V1")

In [12]:
from usta_tokenizer import UstaTokenizer

tokenizer = UstaTokenizer("tokenizer.json")

In [13]:
import torch
torch.manual_seed(1)
embeddings  = torch.nn.Embedding(num_embeddings = 64,embedding_dim = 4)


In [14]:
sentence = "Artificial is intelligence is transforming the way people the interact with technology"

In [15]:
tokens = tokenizer.encode(sentence)

tokens

tensor([ 1, 63,  3, 63,  2, 63,  3, 63,  4, 63,  5, 63,  6, 63,  7, 63,  5, 63,
         8, 63,  9, 63, 10])

In [16]:
meanings = embeddings(torch.tensor(tokens))
meanings.shape

/var/folders/7p/7hglmwtd48d84m9fb6n55grr0000gn/T/ipykernel_35781/2458232116.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  meanings = embeddings(torch.tensor(tokens))


torch.Size([23, 4])

In [17]:
sentences = [
    {
        "words" : meanings.detach().numpy(),
        "labels" : tokenizer.tokenize(sentence),
        "color": "red",
    }
]
plot_dots(sentences,"Sözlük V1")

In [18]:
import numpy as np 

In [19]:
import numpy as np
import torch

tokens = np.array(tokens)


pos_embeddings = torch.nn.Embedding(
    num_embeddings=len(tokens),
    embedding_dim=4
)

pos_meanings = pos_embeddings(
    torch.tensor([i for i in range(tokens.shape[0])])
)

print(pos_meanings.shape)
pos_meanings

torch.Size([23, 4])


/var/folders/7p/7hglmwtd48d84m9fb6n55grr0000gn/T/ipykernel_35781/1243102466.py:4: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  tokens = np.array(tokens)


tensor([[-1.2560,  0.8956,  0.1675,  0.7514],
        [ 2.4142,  1.0206, -0.4405, -1.7342],
        [-1.2362,  1.5786, -1.1161,  0.7678],
        [-0.5882,  2.1189, -0.5422, -2.4593],
        [-1.1108, -1.1187,  0.7580, -0.4957],
        [-0.1970, -0.0334,  0.7193,  1.0644],
        [ 0.8340, -1.9162, -0.3420, -0.6605],
        [ 0.3151,  1.1423,  0.3055, -0.5789],
        [-0.2383, -1.3542,  0.2687,  0.1146],
        [-1.5563, -1.0757, -0.8752, -0.4728],
        [ 0.9912, -0.0586,  1.1788,  0.6222],
        [ 0.7879,  1.3686, -0.8507,  0.5126],
        [ 1.0476, -0.3176,  0.1395,  2.3403],
        [-0.6116,  0.8160,  0.2477, -0.3867],
        [ 0.1995,  0.7993, -0.2619,  0.1513],
        [ 1.1982, -2.2833, -1.0130, -0.8879],
        [ 0.6522, -0.8726,  0.0353, -0.3365],
        [ 1.4023,  0.4841, -0.7030, -0.8268],
        [ 0.7744,  0.6920, -1.0185, -0.8034],
        [ 0.2936, -0.4139, -0.0960, -1.3281],
        [ 0.2324,  0.8615,  0.6218, -1.7812],
        [-0.0339, -0.5396, -1.8074

In [20]:
print("context_length:", context_length)
print("tokens:", tokens)
print("type(tokens):", type(tokens))
print("len(tokens):", len(tokens))

if hasattr(tokens, "shape"):
    print("shape:", tokens.shape)

print(torch.tensor([i for i in range(len(tokens))]))

context_length: 32
tokens: [ 1 63  3 63  2 63  3 63  4 63  5 63  6 63  7 63  5 63  8 63  9 63 10]
type(tokens): <class 'numpy.ndarray'>
len(tokens): 23
shape: (23,)
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22])


In [21]:
print(context_length)
print(tokens.shape)
print(tokens)

32
(23,)
[ 1 63  3 63  2 63  3 63  4 63  5 63  6 63  7 63  5 63  8 63  9 63 10]


In [22]:
meanings_in_context = meanings + pos_meanings
meanings_in_context.shape

torch.Size([23, 4])

In [23]:
sentences = [
    {
        "words" : meanings.detach().numpy(),
        "labels" : tokenizer.tokenize(sentence),
        "color": "red",
    }
]
plot_dots(sentences,"Sentence Context V1")

In [24]:
p_embeddings = torch.zeros(context_length,4,device="cpu")
p_embeddings

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
import math
import torch

def get_position_encoding(context_length,embedding_dim,base=10000,device ="cpu"):
    p_embeddings = torch.zeros(context_length,embedding_dim,device=device)
    for pos in range(context_length):
        for i in range(0,embedding_dim//2):
            p_embeddings[pos,2*i] = math.sin(pos/(base**(2*i/embedding_dim)))
            if i+1 < embedding_dim:
                p_embeddings[pos,2*i+1] = math.cos(pos / (base**(2*i +1/embedding_dim)))
    return p_embeddings.unsqueeze(0)

In [27]:
pos_embeddings = get_position_encoding(23,4)
pos_embeddings.shape
pos_embeddings

tensor([[[ 0.0000,  1.0000,  0.0000,  1.0000],
         [ 0.8415,  0.9950,  0.0100,  1.0000],
         [ 0.9093,  0.9801,  0.0200,  1.0000],
         [ 0.1411,  0.9553,  0.0300,  1.0000],
         [-0.7568,  0.9211,  0.0400,  1.0000],
         [-0.9589,  0.8776,  0.0500,  1.0000],
         [-0.2794,  0.8253,  0.0600,  1.0000],
         [ 0.6570,  0.7648,  0.0699,  1.0000],
         [ 0.9894,  0.6967,  0.0799,  1.0000],
         [ 0.4121,  0.6216,  0.0899,  1.0000],
         [-0.5440,  0.5403,  0.0998,  1.0000],
         [-1.0000,  0.4536,  0.1098,  1.0000],
         [-0.5366,  0.3624,  0.1197,  1.0000],
         [ 0.4202,  0.2675,  0.1296,  1.0000],
         [ 0.9906,  0.1700,  0.1395,  1.0000],
         [ 0.6503,  0.0707,  0.1494,  1.0000],
         [-0.2879, -0.0292,  0.1593,  1.0000],
         [-0.9614, -0.1288,  0.1692,  1.0000],
         [-0.7510, -0.2272,  0.1790,  1.0000],
         [ 0.1499, -0.3233,  0.1889,  1.0000],
         [ 0.9129, -0.4161,  0.1987,  1.0000],
         [ 0.

In [28]:
meanings.shape

torch.Size([23, 4])

In [29]:
meanings_in_sentence = meanings + pos_meanings
meanings_in_sentence

tensor([[-1.3562,  0.2864, -0.8123, -0.8577],
        [ 2.3086, -0.1591, -0.5313, -1.1711],
        [-1.4585,  3.2657, -0.8876,  1.2354],
        [-0.6939,  0.9392, -0.6330, -1.8961],
        [-1.8230, -0.8150, -0.0193, -0.7471],
        [-0.3026, -1.2131,  0.6285,  1.6275],
        [ 0.6118, -0.2291, -0.1136, -0.1929],
        [ 0.2094, -0.0374,  0.2147, -0.0158],
        [-0.9353, -2.5149,  0.9682,  0.3136],
        [-1.6619, -2.2554, -0.9660,  0.0903],
        [ 1.8569,  0.1858,  0.5159,  1.4295],
        [ 0.6822,  0.1889, -0.9415,  1.0757],
        [ 2.1493, -0.4935, -2.1061,  0.8938],
        [-0.7173, -0.3637,  0.1569,  0.1764],
        [ 0.2606,  0.1815, -1.0600,  0.0197],
        [ 1.0925, -3.4630, -1.1037, -0.3248],
        [ 1.5179, -0.6282, -0.6277,  0.4708],
        [ 1.2967, -0.6956, -0.7938, -0.2637],
        [ 2.6537,  0.6199, -0.8607, -1.5768],
        [ 0.1880, -1.5936, -0.1868, -0.7650],
        [ 0.4314,  0.9072,  0.7747, -2.2569],
        [-0.1395, -1.7193, -1.8982

In [30]:
sentences = [
    {
        "words" : meanings_in_sentence.detach().numpy(),
        "labels" : tokenizer.tokenize(sentence) ,
        "color": "red",
    },
    {
        "words" : meanings.detach().numpy(),
        "labels" : tokenizer.tokenize(sentence) ,
        "color": "blue",
    }
]
plot_dots(sentences,"Sentence Context Space V2")

In [31]:
print(tokenizer.tokenize(sentence))

['artificial', ' ', 'is', ' ', 'intelligence', ' ', 'is', ' ', 'transforming', ' ', 'the', ' ', 'way', ' ', 'people', ' ', 'the', ' ', 'interact', ' ', 'with', ' ', 'technology']


In [32]:
print(tokenizer.tokenize("Artificial is intelligence"))

['artificial', ' ', 'is', ' ', 'intelligence']


In [33]:
freqs_indices = torch.arange(0 ,20 ,dtype = torch.float32)
freqs = 1.0 /(10000 **(freqs_indices /20))
freqs.unsqueeze(0).shape

torch.Size([1, 20])

In [34]:
def get_rotary_position_encoding(input: torch.Tensor , base = 10000, device="cpu"):
    context_length,dimension = input.shape

    assert dimension % 2 == 0 , "dimension must be even"

    half_dimension = dimension // 2

    freqs_indices = torch.arange(0,half_dimension , device = device,dtype = torch.float32)

    freqs = 1.0 / (base ** (freqs_indices / dimension))

    positions = torch.arange(0,context_length,device=device ,dtype = torch.float32).unsqueeze(1)

    angles = positions * freqs

    sin_angles = torch.sin(angles)
    cos_angles = torch.cos(angles)

    input_even = input[: ,0::2]
    input_odd = input[: , 1::2]

    input_even_rotated = input_even * cos_angles - input_odd * sin_angles
    input_odd_rotated = input_even * sin_angles + input_odd * cos_angles

    input_rotated = torch.empty_like(input)

    input_rotated[:, 0::2] = input_even_rotated 
    input_rotated[: , 1::2] = input_odd_rotated

    return input_rotated


get_rotary_position_encoding(torch.randn(23,4))



tensor([[-1.5521, -0.6490, -0.0774, -0.6042],
        [-1.1156,  0.0352,  0.1392, -1.3778],
        [-0.8607, -0.6005, -0.1499, -0.5121],
        [-1.2531,  0.4985, -0.0074, -0.6057],
        [ 0.3720,  0.7705, -1.9375, -0.0267],
        [-0.3108,  0.4940,  1.9889, -0.5031],
        [ 0.6625,  0.1523, -0.5196, -1.1164],
        [-1.4180,  1.2141,  0.0366, -0.0919],
        [-1.0712, -1.8560, -0.6737,  0.8471],
        [ 0.2623,  1.5739, -0.6063, -0.8119],
        [-0.8619, -1.0595,  0.1360,  2.7994],
        [ 1.1941,  0.6334,  0.6824,  0.3382],
        [ 1.4347, -0.2151, -1.7486, -0.6664],
        [-0.5469,  0.0979, -0.7558, -0.1585],
        [ 0.2736,  0.7902,  0.5954, -0.9705],
        [ 1.5770,  1.6967, -0.4651,  0.5909],
        [-0.2341,  1.0213, -0.4811,  0.5996],
        [ 1.1120, -1.2945, -0.2989,  1.4822],
        [-1.1317,  0.7571,  0.7998, -0.7419],
        [-0.6953, -0.1700,  0.1761,  1.1969],
        [-0.7447, -1.4372,  0.8606, -1.1345],
        [ 0.2613,  0.4929, -1.0831

In [35]:
torch.manual_seed(1)
random_input = torch.randn(23,4)
pos_rotary_encodings = get_rotary_position_encoding(random_input)
pos_rotary_encodings


tensor([[-1.5256, -0.7502, -0.6540, -1.6095],
        [ 0.4585, -0.4134, -0.8142, -1.6989],
        [ 0.0202, -0.7739, -0.7119, -0.4009],
        [-0.0180, -1.7016,  0.0800,  0.5143],
        [-0.4229,  1.2862,  0.5668,  0.4558],
        [ 0.4799, -0.7608, -0.9688,  0.3907],
        [ 1.0086, -0.4768, -1.0366, -2.4618],
        [ 0.4520, -0.4255, -0.5256, -0.6148],
        [-0.2021,  1.8698,  0.6648, -0.4257],
        [-0.2002,  0.0404,  0.4677, -0.1759],
        [ 0.2524, -0.1852, -0.0611, -0.1484],
        [-1.0269, -2.3617,  1.2756,  1.1178],
        [-0.4901,  0.9576,  0.4314, -0.0966],
        [ 0.5065,  0.7211, -1.6303,  1.6618],
        [-0.9110,  0.2645,  0.6036, -0.2929],
        [-0.6039,  1.6616,  0.5104, -3.3757],
        [-0.2702,  0.9873,  1.0225, -0.5666],
        [ 0.0507,  0.2046, -0.2259,  1.6581],
        [-0.6040,  0.4063,  1.0359, -0.7813],
        [ 1.4670, -0.9537,  0.1157,  0.1660],
        [-0.8164,  1.0894,  0.4909,  1.1226],
        [-0.4454, -0.7144,  0.9565

In [36]:
meanings.shape

torch.Size([23, 4])

In [37]:
meanings_with_pos_encodings = get_rotary_position_encoding(meanings)

In [38]:
meanings_with_pos_encodings.shape

torch.Size([23, 4])

In [40]:
sentences = [
    {
        "words" : meanings_with_pos_encodings.detach().numpy(),
        "labels" : tokenizer.tokenize(sentence),
        "color" : "red",
    },
    {
    
        "words" : meanings.detach().numpy(),
        "labels" : tokenizer.tokenize(sentence),
        "color" : "blue",
    },
]
plot_dots(sentences,"Sentence Context Space V3 Rotary Encoding")

## Model olarak şimdiye kadar yaptığımızı kullanabiliriz 

In [41]:
from usta_model import UstaModel
from usta_tokenizer import UstaTokenizer

u_tokenizer = UstaTokenizer("tokenizer.json")

prompt = "Artificial is intelligence is transforming the way people the interact with technology"
tokens = u_tokenizer.encode(prompt)

model = UstaModel(vocab_size=len(u_tokenizer.vocab),embedding_dim = 4,context_length= 23)

model

UstaModel(
  (embedding): Embedding(65, 4)
  (pos_embedding): Embedding(23, 4)
)

In [45]:
model(tokens)

tensor([[ 8.7380e-01, -5.6026e-01,  1.2858e+00,  8.1682e-01],
        [ 9.7479e-01,  9.3198e-01, -1.2762e-01, -5.9216e-01],
        [-8.5236e-01,  2.4232e+00, -3.8285e-01,  1.8209e+00],
        [-1.2531e+00,  4.9853e-01, -7.4365e-03, -6.0571e-01],
        [ 1.6694e-03,  1.9341e+00,  4.2349e-01,  1.8796e+00],
        [ 6.8160e-02, -1.3469e+00,  1.1305e-01, -5.9511e-01],
        [ 2.3910e+00, -9.3885e-01, -1.0617e+00,  1.5280e+00],
        [ 1.1964e+00,  6.2249e-01,  2.2903e-01, -5.6079e-01],
        [-5.6940e-01,  1.4825e+00, -3.7619e-01,  4.9501e-01],
        [-1.0639e+00,  8.2882e-01,  3.3587e-01, -5.0411e-01],
        [-1.5642e+00,  1.1031e+00, -8.1825e-01,  9.4592e-01],
        [-3.1090e-01, -1.3123e+00,  4.2933e-01, -4.2734e-01],
        [-9.3374e-01, -1.4104e-01,  6.5297e-01, -4.9863e-01],
        [ 1.3227e+00,  2.6341e-01,  5.0567e-01, -3.3352e-01],
        [ 1.6337e+00, -1.8519e+00, -5.5876e-01,  6.4748e-01],
        [-7.8994e-01,  1.0931e+00,  5.6185e-01, -2.2642e-01],
        